local e = game:eventBarn():AddEventByMetaName("SoaringOverCalifornia")
e:bonkAvoidanceMult(1.0)
e:hover(true)
e:maxSpeed(20)
e:yawMult(1.0)
e:minSpeed(0.2)
e:pitchMult(1.0)
e:groundDist(50)
e:Start()
