local e = game:eventBarn():AddEventByMetaName("SoaringOverCalifornia")
e:bonkAvoidanceMult(1.2)
e:hover(false)
e:maxSpeed(40.5)
e:yawMult(2.5)
e:minSpeed(26.5)
e:pitchMult(2)
e:groundDist(3.5)
e:Start()
